# Prometheus Configuration for AI Automation Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'multifamily-ai'
    environment: 'production'

# Alerting rules
rule_files:
  - "alerts.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # Main Application
  - job_name: 'multifamily-ai-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # AI Monitor Service
  - job_name: 'ai-monitor'
    static_configs:
      - targets: ['ai-monitor:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # AI Optimizer Service
  - job_name: 'ai-optimizer'
    static_configs:
      - targets: ['ai-optimizer:8001']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Nginx Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s

  # Health Check Metrics
  - job_name: 'health-checks'
    file_sd_configs:
      - files:
          - '/app/tmp/health-metrics.json'
        refresh_interval: 30s